project:
  type: website
website:
  title: "yHat"
  site-url: https://www.rsangole.com
  description: "rahul's blog on data science"
  twitter-card:
    creator: "@rsangole"
  navbar:
    right:
      - href: index.qmd
        text: ~/
      - href: blog.qmd
        text: ~/blog
      - href: talks.qmd
        text: ~/talks
      # - href: career.qmd
      #   text: ~/career
      - href: astronomy.qmd
        text: ~/astronomy
  page-footer:
    center: "2025 rahul-s"
  google-analytics: "UA-106573867-1"
format:
  html:
    theme: simplex