baseurl = "/"
relativeURLs = true
languageCode = "en-us"
title = "pHack"
theme = "hugo-xmin"
disqusShortname = "rsangole-netlify-com" # delete this to disable disqus comments
googleAnalytics = "UA-106573867-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
enableEmoji = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "posts"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "projects"
    url = "/project/"
    weight = 3
[[menu.main]]
    name = "github"
    url = "https://http://github.com/rsangole"
    weight = 4

[params]
    author = "Rahul S"
    dateFormat = "2006-01-02"
    description = ""
    footer = "&copy; Rahul S 2020 | [Github](https://www.github.com/rsangole)"
