baseurl = "/"
relativeURLs = true
languageCode = "en-us"
title = "{yHat}"
theme = "hugo-xmin"
disqusShortname = "rsangole-netlify-com" # delete this to disable disqus comments
googleAnalytics = "UA-106573867-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
enableEmoji = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "posts"
    url = "/post/"
    weight = 2

[[menu.main]]
    name = "projects"
    url = "/projects/"
    weight = 3

[[menu.main]]
    name = "notes"
    url = "/notes/"
    weight = 4

[[menu.main]]
    name = "topics"
    url = "/categories/"
    weight = 5

[params]
    author = "rahul s"
    dateFormat = "2006-01-02"
    description = "data science blog by rahul sangole"
    footer = "&copy; rahul s 2022 | [Github](https://www.github.com/rsangole)"