FROM hatmatrix/blog:base

ENV MRAN_BUILD_DATE=2021-06-18

# Analysis Packages
RUN install2.r -r https://cran.microsoft.com/snapshot/${MRAN_BUILD_DATE} \
	--error \
	randomForest \
	feasts \
	prophet \
	qcc \
	MSQC \
	Rtsne \
	strucchange \
	robfilter \
	bfast \
	tsmp \
	anomalize \
	slider \
	dtwclust \
	fpp3 \
	astsa \
	cluster \
	dendextend \
	rpart \
	party \
	partykit \
	fable \
	tidymodels \
	modeltime \
	timetk