project:
  type: website

website:
  title: "yHat"
  site-url: https://www.rsangole.com
  description: "rahul's blog on data science"
  twitter-card:
    creator: "@rsangole"
  navbar:
    right:
      - href: index.qmd
        text: ~/
      - href: blog.qmd
        text: /blog/
  page-footer:
    center: "2022 rahul s"

format:
  html:
    theme: simplex
    css: styles.css
    toc: true



